### ISSUE TITLE
【草稿箱】草稿箱的表结构

### ISSUE THREAD

**Issue by Linklinkguan** [smart-signature/smart-signature-backend#10]
## 草稿箱系统设计
![image](https://user-images.githubusercontent.com/10827774/55872333-538ad780-5bbf-11e9-9d7b-789781259aa1.png)
![image](https://user-images.githubusercontent.com/10827774/55872360-62718a00-5bbf-11e9-9112-1b439de0543e.png)
![image](https://user-images.githubusercontent.com/10827774/55872377-69989800-5bbf-11e9-85dc-0e588665b76b.png)
## 需求
带TOKEN的API：基于用户id获得草稿箱的标题和草稿id列表。/draft/getDraftList
带TOKEN的API：基于用户id，草稿箱草稿id，获得草稿的内容等详细信息。/draft/getDraftDetail
带TOKEN的API：基于用户id，草稿id（如果有）写入草稿。参数不带草稿id，则创建新的。/draft/setDraft
带TOKEN的API：基于用户id，草稿id删除某个草稿（标记位，不是delete）。/draft/deleteDraft

**Comment by AkemiKusane** [comment]
等待需求确认，暂缓
