### ISSUE TITLE
stage 和 localhost 拿不到最新数据

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-backend#5]
![WechatIMG2](https://user-images.githubusercontent.com/2507027/55275497-f6bb3180-5321-11e9-983c-97ee54a9a5cf.jpeg)

目前 stage 和 localhost 拿不到最新 3 天的文章和统计数据。我想知道这是 符合预期 的吗？我记得我早上是可以看到的。

**Comment by lychees** [comment]
Stage 数据有误。

https://sign-dev.dravatar.xyz/article/QmNStW94L1K8298uH3oXwaaJacxLYwFqnBRYHvzrQ3uUwE?invite=xiaotiandada

**Comment by jc1991x** [comment]
数据库分离的关系。
