### ISSUE TITLE
[改 善 请 求] 开启 egg-cors 的 allowMethods

### ISSUE THREAD

**Issue by frankwei98** [smart-signature/smart-signature-backend#9]
你好，这里是前端的 Frank。

我们打算使用 `async` `await` 代替 callback，目前普遍用的是 `axios` 这个 library 来处理 。

但因为 `axios` 让浏览器发起 POST 请求需要一个 OPTIONS preflight (然后浏览器知道后端支持哪些HTTP方法了）

而后端目前看起来还不支持 OPTIONS ，所以我们暂时无法在前端用 axios

![新后端](https://user-images.githubusercontent.com/3261732/55525062-2bccd880-56c2-11e9-8e3f-31aab4a1c7d9.png)

Google 了一下，看起来已经安装的依赖 `egg-cors` 刚好可以解决这个问题

目前我们用到的应该是 `GET` 和 `POST`

![老的后端](https://user-images.githubusercontent.com/3261732/55525292-2328d200-56c3-11e9-9e58-6fe3f21c2709.png)

请问可以在后端开启 allowMethods 吗？

参考：https://github.com/eggjs/egg-cors#configuration

**Comment by jc1991x** [comment]
OPTIONS 不在 allowMethods里面吧。 

之前用不了axios ， 原因应该某些axios的参数没填对，

目前的前端项目代码里，看起来已经可以正常使用axios了。
